export const GET_ALL_GALLERY = "GET_ALL_GALLERY";
export const HIDE_GALLERY_PRELOADER = "HIDE_GALLERY_PRELOADER";
export const SHOW_GALLERY_PRELOADER = "SHOW_GALLERY_PRELOADER";
export const FILTER_GALLERY_BY_COMMENTS = "FILTER_GALLERY_BY_COMMENTS";
export const FILTER_GALLERY_BY_SCORE = "FILTER_GALLERY_BY_SCORE";
